question_data = [{"type":"boolean","difficulty":"easy","category":"Geography","question":"Nova Scotia is on the east coast of Canada.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.","correct_answer":"True","incorrect_answers":["False"]}
                            ,{"type":"boolean","difficulty":"easy","category":"Geography","question":"Toronto is the capital city of the North American country of Canada.","correct_answer":"False","incorrect_answers":["True"]}
                            ,{"type":"boolean","difficulty":"easy","category":"Geography","question":"There is a city called Rome in every continent on Earth.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"There are no deserts in Europe.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"Rhode Island is actually located on the US mainland, despite its name.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"Ottawa is the capital of Canada.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"New Haven is the capital city of the state of Connecticut in the United States.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"Alaska is the largest state in the United States.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"Vatican City is a country.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"Tokyo is the capital of Japan.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"easy","category":"Geography","question":"San Marino is the only country completely surrounded by another country.","correct_answer":"False","incorrect_answers":["True"]}
                            ,{"type":"boolean","difficulty":"easy","category":"Geography","question":"Greenland is covered with grass and Iceland covered with ice.","correct_answer":"False","incorrect_answers":["True"]}]